// packages/taro-vue/src/components/Navbar/index.vue
<template>
  <view class='fish-navbar'>
    <view
      :class="{ 'fish-navbar__fixed': props.fixed }"
      :style="{ backgroundColor: props.backgroundColor }"
    >
      <view :style="{ height: `${statusBarHeight}px` }" />
      <view v-if="height !== 0" class='fish-navbar__header' :style="{ height, backgroundColor: props.backgroundColor }">
        <view v-if="!props.hideBack" class='fish-navbar__header-left'>
          <view v-if="!slots.left" class='fish-navbar__goback' @tap="handleBack">
            <image :src="props.backIcon!" class='fish-navbar__icon' />
          </view>
          <block v-else>
            <slot name="left" />
          </block>
              
        </view>
        <view class='fish-navbar__header-wrap'>
          <text v-if="!slots.title" :style="{ color: props.color }">{{props.title}}</text>
          <block v-else>
            <slot name="title" />
          </block>
        </view>
      </view>
    </view>
    <view class='fish-navbar__placeholder'>
      <view :style="{height: `${statusBarHeight}px`}" />
      <view :style="{ height }" />
    </view>
  </view>
</template>

<script lang="ts" setup>
import { withDefaults, defineProps, useSlots, computed } from 'vue';
import Taro from '@tarojs/taro';
import { getSizeToPx } from '../../utils';
import iconPath from '../../../../../assets/icon-back.png';

interface IProps {
  title?: string;
  backIcon?: string;
  color?: string;
  backgroundColor?: string;
  fixed?: boolean;
  height?: number;
  hideBack?: boolean;
  goback?: (e: any) => void; // eslint-disable-line no-unused-vars
};

const props = withDefaults(defineProps<IProps>(), {
  title: '',
  backIcon: iconPath,
  color: '#222222',
  backgroundColor: '#FFFFFF',
  fixed: true,
  height: 44,
  hideBack: false,
});

const { statusBarHeight } = Taro.getSystemInfoSync();

const slots = useSlots();

const handleBack = (e) => {
  if (typeof props.goback === 'function') {
    props.goback(e);
  } else {
    Taro.navigateBack();
  }
};

const height = computed(() => getSizeToPx(props.height));

</script>

// packages/taro-react/src/components/Navbar/index.tsx
import * as React from 'react';
import Taro from '@tarojs/taro';
import { Image, View, Text } from '@tarojs/components';
import { getSizeToPx } from '../../utils';
import iconPath from '../../../../../assets/icon-back.png';

type INavbarProps = React.PropsWithChildren<{
  title?: string;
  backIcon?: string;
  color?: string;
  backgroundColor?: string;
  fixed?: boolean;
  height?: number;
  hideBack?: boolean;
  goback?: (e: any) => void;
  renderLeft?: () => React.ReactNode;
  renderTitle?: () => React.ReactNode;
}>;

const { statusBarHeight } = Taro.getSystemInfoSync();

const Navbar: React.FC<INavbarProps> = (props) => {
  const fixedClass = props.fixed ? 'fish-navbar__fixed' : '';
  const statusBarStyle: React.CSSProperties = {
    height: `${statusBarHeight}px`,
  };
  const height = getSizeToPx(props.height!);

  const handleBack = (e) => {
    if (typeof props.goback === 'function') {
      props.goback(e);
    } else {
      Taro.navigateBack();
    }
  };

  return (
    <View className='fish-navbar'>
      <View className={fixedClass} style={{ backgroundColor: props.backgroundColor }}>
        <View style={statusBarStyle} />
        {
          height !== 0 && (
            <View className='fish-navbar__header' style={{ height, backgroundColor: props.backgroundColor }}>
              {
                !props.hideBack && (
                  <View className='fish-navbar__header-left'>
                    {
                      !props.renderLeft ? (
                        <View className='fish-navbar__goback' onTouchstart={handleBack}>
                          <Image
                            src={props.backIcon}
                            className='fish-navbar__icon'
                          />
                        </View>
                      ) : props.renderLeft()
                    }
                  </View>
                )
              }
              <View className='fish-navbar__header-wrap'>
                {
                  !props.renderTitle ? <Text style={{ color: props.color }}>{props.title}</Text> : props.renderTitle()
                }
              </View>
            </View>
          )
        }
      </View>
      {
        props.fixed && (
          <View className='fish-navbar__placeholder'>
            <View style={statusBarStyle} />
            <View style={{ height }} />
          </View>
        )
      }
    </View>
  )
};

Navbar.defaultProps = {
  title: '',
  color: '#222222',
  backgroundColor: '#FFFFFF',
  fixed: true,
  height: 44,
  hideBack: false,
  backIcon: iconPath,
}

export default Navbar;

export type {
  INavbarProps
}
